version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
      MYSQL_DATABASE: fti_perpus_dev
      MYSQL_USER: ftiperpus
      MYSQL_PASSWORD: ftipassword
    volumes:
      - mysqlvolume:/var/lib/mysql
    networks:
      - fti_perpus_network
  
  api:
    build: ./backend-app
    container_name: api
    restart: unless-stopped
    tty: true
    ports:
      - 8000:8000
    networks:
      - fti_perpus_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=fti_perpus_dev
      - DB_USERNAME=ftiperpus
      - DB_PASSWORD=ftipassword
    depends_on:
      - db

  web:
    build: ./frontend-app
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - 3000:4173
    networks:
      - fti_perpus_network
    depends_on:
      - api

volumes:
  mysqlvolume:
    driver: local

networks:
  fti_perpus_network:
    driver: bridge
